/******************************************* ***********/
/************** © 2018 ISG - All Rights Reserved     ***********/
/******************************************************/

/*******************************************************/
/** File Name:compare-data.ts **/
/** Description:  **/
/** Created By: 106##### Created Date: 28/09/2018 **/
/** Update By:  106##### Update Date:  28/09/2018 **/
/** Developed at:  **/
/*******************************************************/

export interface CompareData {
    industries:[
        {
            label:string
        }
    ],
    dataset:[
        {
            itSpendCompanyRev:[
                {
                    value:number
                }
            ]
        },
        {
            itSpendBreakdown:{
                infrastructure:[
                    {
                        value:number
                    }
                ],
                application:[
                    {
                        value:number
                    }
                ],
                management:[
                    {
                        value:number
                    }
                ]
            }
        },
        {
            itSpendPerUser:[
                {
                    value:number
                }
            ]
        },
        {
            itSpendByExpnditure:{
                personnel:[
                    {
                        value:number
                    }
                ],
                hardware:[
                    {
                        value:number
                    }
                ],
                software:[
                    {
                        value:number
                    }
                ],
                outsourced:[
                    {
                        value:number
                    }
                ],
                other:[
                    {
                        value:number
                    }
                ]
            }
        },
        {
            itSpendOutsourced:[
                {
                    value:number
                }
            ]
        },
        {
            capexVsOpex:{
                overallCapex:[
                    {
                        value:number
                    }
                ],
                overallOpex:[
                    {
                        value:number
                    }
                ]
            }
        },
        {
            itRunVsChangeVsTransform:{
                run:[
                    {
                        value:number
                    }
                ],
                change:[
                    {
                        value:number
                    }
                ],
                transform:[
                    {
                        value:number
                    }
                ]
            }
        },
        {
            itPersonnel:{
                totalEmployeesPerc:[
                    {
                        value:number
                    }
                ],
                totalContractorsPerc:[
                    {
                        value:number
                    }
                ],
                onshore:[
                    {
                        value:number
                    }
                ],
                offshore:[
                    {
                        value:number
                    }
                ],
                attritionRate:[
                    {
                        value:number
                    }
                ]
            }
        },
        {
            userExperience:{
                overallSatisfaction:[
                    {
                        value:number
                    }
                ]
            }
        },
        {
            digitalSpend:{
                percentOfSGA:[
                    {
                        value:number
                    }
                ]
            }
        }
    ]
}
